-file("/home/josh/Playground/erlangs/lib/parsetools-2.0.11/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(command_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/command_lexer.xrl", 71).

atom(Chars) when is_atom(Chars) -> Chars;
atom(Chars) -> list_to_atom(Chars).

strip(TokenChars,TokenLen) ->
    lists:sublist(TokenChars, 2, TokenLen - 2).

-file("/home/josh/Playground/erlangs/lib/parsetools-2.0.11/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/command_lexer.erl", 282).
yystate() -> 93.

yystate(96, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 2, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 2, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 2, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 2, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,96};
yystate(95, [10|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line+1, Tlen+1, 30, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(95, Ics, Line, Tlen+1, 30, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(95, Ics, Line, Tlen+1, 30, Tlen);
yystate(95, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,95};
yystate(94, [116|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, [84|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,94};
yystate(93, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [87|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [86|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [74|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [71|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 75, C =< 77 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 80, C =< 82 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 88, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 107, C =< 109 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 114 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, [C|Ics], Line, Tlen, Action, Alen) when C >= 120, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(93, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,93};
yystate(92, [101|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, [69|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,92};
yystate(91, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(90, [114|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, [82|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,90};
yystate(89, [104|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, [72|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 71 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,89};
yystate(88, [114|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, [82|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,88};
yystate(87, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [101|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, [69|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,86};
yystate(85, [101|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, [69|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,85};
yystate(84, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 8, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 8, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 8, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 8, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,84};
yystate(83, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(82, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 11, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 11, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 11, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 11, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,82};
yystate(81, [114|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [82|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,81};
yystate(80, [114|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, [82|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,80};
yystate(79, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [111|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, [79|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,78};
yystate(77, [101|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, [69|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,77};
yystate(76, [111|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, [79|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,76};
yystate(75, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(74, [116|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [115|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [110|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [84|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [83|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [78|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 82 ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 18, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,74};
yystate(73, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 5, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 5, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 5, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 5, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,73};
yystate(72, [117|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, [85|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,72};
yystate(71, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [110|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, [78|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,70};
yystate(69, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,69};
yystate(68, [112|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, [80|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 79 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 81, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(66, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 10, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 10, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 10, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 10, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,66};
yystate(65, [112|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, [80|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 79 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 81, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,65};
yystate(64, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(62, [110|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, [78|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,62};
yystate(61, [100|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, [68|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,61};
yystate(60, [114|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [97|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [82|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [65|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,60};
yystate(59, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, [105|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, [73|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,58};
yystate(57, [97|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 22, Tlen);
yystate(57, [65|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 22, Tlen);
yystate(57, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,57};
yystate(56, [111|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, [79|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,56};
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [111|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, [79|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,54};
yystate(53, [116|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, [84|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,53};
yystate(52, [109|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, [77|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 76 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 78, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,52};
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, 25, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,51};
yystate(50, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 21, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 21, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 21, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 21, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,50};
yystate(49, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, [69|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,49};
yystate(48, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,48};
yystate(47, [101|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 25, Tlen);
yystate(47, [69|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 25, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, 25, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,47};
yystate(46, [108|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, [76|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,46};
yystate(45, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 1, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 1, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 1, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 1, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,45};
yystate(44, [108|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, [76|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,44};
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, [108|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, [76|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,42};
yystate(41, [114|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, [82|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,41};
yystate(40, [115|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, [83|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,40};
yystate(39, [46|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 26, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, 26, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,39};
yystate(38, [117|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, [85|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,38};
yystate(37, [117|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, [85|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,37};
yystate(36, [101|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, [69|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,36};
yystate(35, [61|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 28, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,35};
yystate(34, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 6, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 6, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 6, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 6, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,34};
yystate(33, [101|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, [69|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,33};
yystate(32, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 20, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 20, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 20, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 20, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,32};
yystate(31, [62|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 28, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,31};
yystate(30, [114|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, [82|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,30};
yystate(29, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,29};
yystate(28, [101|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, [69|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,28};
yystate(27, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 17, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,27};
yystate(26, [101|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, [69|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,26};
yystate(25, [101|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, [69|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,25};
yystate(24, [115|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [108|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [83|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [76|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 82 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 114 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,24};
yystate(23, [100|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, [68|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,23};
yystate(22, [100|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [68|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(69, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(69, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 16, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,22};
yystate(21, [116|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [108|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [84|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [76|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 83 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,21};
yystate(20, [99|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [97|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [98|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [67|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [65|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [66|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,20};
yystate(19, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 14, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,19};
yystate(18, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 9, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 9, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 9, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 9, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,18};
yystate(17, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 12, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,17};
yystate(16, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,16};
yystate(15, [99|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [97|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [98|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [67|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [65|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [66|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,15};
yystate(14, [114|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, [82|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,14};
yystate(13, [101|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, [69|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,13};
yystate(12, [101|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, [69|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,12};
yystate(11, [115|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [110|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [83|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [78|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 82 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,11};
yystate(10, [101|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, [69|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,10};
yystate(9, [99|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [97|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [98|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [67|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [65|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [66|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,9};
yystate(8, [116|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, [84|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,8};
yystate(7, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 15, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 15, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 15, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 15, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,7};
yystate(6, [116|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [84|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,6};
yystate(5, [116|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, [84|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,5};
yystate(4, [101|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, [69|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,4};
yystate(3, [122|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, [121|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, [90|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, [89|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 88 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,3};
yystate(2, [117|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [115|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [116|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [114|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [85|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [83|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [84|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [82|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 22, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,2};
yystate(1, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 0, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 0, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 0, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 0, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,1};
yystate(0, [46|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 3, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(69, Ics, Line, Tlen+1, 3, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(69, Ics, Line, Tlen+1, 3, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(69, Ics, Line, Tlen+1, 3, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLen, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLen, TokenLine);
yyaction(25, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLen);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, _) ->
    yyaction_30();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/command_lexer.xrl", 37).
yyaction_0(TokenLine) ->
     { token, { select, TokenLine } } .

-compile({inline,yyaction_1/1}).
-file("src/command_lexer.xrl", 38).
yyaction_1(TokenLine) ->
     { token, { update, TokenLine } } .

-compile({inline,yyaction_2/1}).
-file("src/command_lexer.xrl", 39).
yyaction_2(TokenLine) ->
     { token, { insert, TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("src/command_lexer.xrl", 40).
yyaction_3(TokenLine) ->
     { token, { delete, TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("src/command_lexer.xrl", 41).
yyaction_4(TokenLine) ->
     { token, { from, TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("src/command_lexer.xrl", 42).
yyaction_5(TokenLine) ->
     { token, { where, TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("src/command_lexer.xrl", 43).
yyaction_6(TokenLine) ->
     { token, { order, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("src/command_lexer.xrl", 44).
yyaction_7(TokenLine) ->
     { token, { group, TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("src/command_lexer.xrl", 45).
yyaction_8(TokenLine) ->
     { token, { inner, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/command_lexer.xrl", 46).
yyaction_9(TokenLine) ->
     { token, { outer, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("src/command_lexer.xrl", 47).
yyaction_10(TokenLine) ->
     { token, { join, TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("src/command_lexer.xrl", 48).
yyaction_11(TokenLine) ->
     { token, { into, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/command_lexer.xrl", 49).
yyaction_12(TokenLine) ->
     { token, { set, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("src/command_lexer.xrl", 50).
yyaction_13(TokenLine) ->
     { token, { desc, TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("src/command_lexer.xrl", 51).
yyaction_14(TokenLine) ->
     { token, { asc, TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("src/command_lexer.xrl", 52).
yyaction_15(TokenLine) ->
     { token, { by, TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("src/command_lexer.xrl", 53).
yyaction_16(TokenLine) ->
     { token, { atom ('or'), TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("src/command_lexer.xrl", 54).
yyaction_17(TokenLine) ->
     { token, { atom ('and'), TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("src/command_lexer.xrl", 55).
yyaction_18(TokenLine) ->
     { token, { in, TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("src/command_lexer.xrl", 56).
yyaction_19(TokenLine) ->
     { token, { bool, TokenLine, true } } .

-compile({inline,yyaction_20/1}).
-file("src/command_lexer.xrl", 57).
yyaction_20(TokenLine) ->
     { token, { bool, TokenLine, false } } .

-compile({inline,yyaction_21/1}).
-file("src/command_lexer.xrl", 58).
yyaction_21(TokenLine) ->
     { token, { null, TokenLine } } .

-compile({inline,yyaction_22/2}).
-file("src/command_lexer.xrl", 59).
yyaction_22(TokenChars, TokenLine) ->
     { token, { var, TokenLine, TokenChars } } .

-compile({inline,yyaction_23/3}).
-file("src/command_lexer.xrl", 60).
yyaction_23(TokenChars, TokenLen, TokenLine) ->
     { token, { string, TokenLine, strip (TokenChars, TokenLen) } } .

-compile({inline,yyaction_24/3}).
-file("src/command_lexer.xrl", 61).
yyaction_24(TokenChars, TokenLen, TokenLine) ->
     { token, { string, TokenLine, strip (TokenChars, TokenLen) } } .

-compile({inline,yyaction_25/2}).
-file("src/command_lexer.xrl", 62).
yyaction_25(TokenChars, TokenLen) ->
     { token, { float, TokenLen, list_to_float (TokenChars) } } .

-compile({inline,yyaction_26/2}).
-file("src/command_lexer.xrl", 63).
yyaction_26(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_27/2}).
-file("src/command_lexer.xrl", 64).
yyaction_27(TokenChars, TokenLine) ->
     { token, { atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_28/2}).
-file("src/command_lexer.xrl", 65).
yyaction_28(TokenChars, TokenLine) ->
     { token, { op, TokenLine, atom (TokenChars) } } .

-compile({inline,yyaction_29/1}).
-file("src/command_lexer.xrl", 66).
yyaction_29(TokenLine) ->
     { token, { all, TokenLine } } .

-compile({inline,yyaction_30/0}).
-file("src/command_lexer.xrl", 67).
yyaction_30() ->
     skip_token .

-file("/home/josh/Playground/erlangs/lib/parsetools-2.0.11/include/leexinc.hrl", 282).
